"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import logo from '../app/images/musiclogo.jpg'
import Link from 'next/link'
import {BiLogIn} from 'react-icons/bi'
import {MdOutlineEvent, MdSubscriptions} from 'react-icons/md'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children}) {


  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <h1>hi</h1> */}
      <nav class="layout">
  <div class="logo">
  <ul className='navbarul'>
        <li className=''>
          <Link href="/">
          <Image src={logo} />
          </Link>
        </li>
      </ul>
  </div>
  <div class="home-event" style={{gridColumn: 2/3}}>
  <ul className='ulNavbar'>
    <Link href="/event">
        <li>
          <MdOutlineEvent size={25} />
          </li>
    </Link>

        <li>
    <Link href="artist">
          <img style={{color:'rgba(151, 71, 255, 1)'}} width="29" height="10" src="https://img.icons8.com/avantgarde/100/dj.png" alt="dj"/>
    </Link>
          </li>

        <li>
          <Link href="/subscri">
          <MdSubscriptions size={25} />
          </Link>
          </li>
      </ul>
  </div>
  <div class="login-button">
  <ul>
        <li><BiLogIn size={25} /></li>
      </ul>
  </div>
</nav>
{children}
      </body>
    </html>
  )
}
